Arcana/materials.json
Arcana/recipe_armor.json
Arcana/tool_armor.json

Added foot coverage to the wyrmskin armor. Changed volume, weight, and recipe to reflect this inclusion. Additionally increased enviornmental resistance and indcreased natural acid resistance of the relevent material.
Additionally added sulphuric acid and nitric acid as crafting options, due to potential rarity of finding generic acid without electronics skill to dismantle batteries.
Reasoning: The item appears to be intended as acid resistant, but at present lack of foot protection prevents this from applying in most cases, due to acid pools being the most common source of acid damage. Likewise, the actual acid protection provided is minimal.

Rebalancing for wyrmskin armor

---

Arcana/recipe_armor.json
Arcana/recipe_others.json
Arcana/recipe_weapon.json

Updates recipes involving the chisel to make use of chisel as a quality instead of a tool. Reasoning is that chiselling tools now make use of qualities and can presumably be used to exclude recipes if makeshift versions are ever implemented.
This change was originally added to the obsolete version of the mod in the Cataclysm DDA repository by another user, see pull request: https://github.com/CleverRaven/Cataclysm-DDA/pull/20081

Changes recipes to use chisel qualities

---

Arcana/furniture.json

This pull request adds the flag that enables deconstruction without tools to the upright weapon.
The relevant pull request is https://github.com/CleverRaven/Cataclysm-DDA/pull/21402
My apologies for having been delayed in porting over this change, but some things came up recently, and I had not been as active as of late.

Adds EASY_DECONSTRUCT flag to upright sword

---

Arcana/armor.json
Arcana/effects.json
Arcana/mapgen_shrines.json
Arcana/overmap_specials.json
Arcana/overmap_terrain.json
Arcana/ranged.json
Arcana/recipe_deconstruction.json
Arcana/tool_armor.json
Arcana/tools.json

Self-PR for the hell of it, makes feedback easier. o3o
* Adds three optional locations full of anomalies, monsters, and other Fun stuff, as sources of some new items.
* Meteoric talisman, your basic passive item that lets you no-sell electricity when worn.
* Moonstone fang. Decent stabbing weapon, can procure sneks and drain life when wielded, with some side effects. Activation lets you straight-up no-sell freezing to death for a while (immunity to being chilly, frostbite, and frostbite recovery).
* Jade wreath. Doesn't do much besides eat fires when worn, but activating it gives immunity to being warm, smoke inhalation, blistering, and catching on fire. Actually standing in fire will still fuck you up though.
* Some assorted effects were removed from existing items now that other …

Ruined shrines, 3 new items

---

Arcana/tool_armor.json

With https://github.com/CleverRaven/Cataclysm-DDA/pull/21758 now mainlined, the mask of insight can now use this flag to make a it a proper tool as discussed. This PR just changes the tag.

Upgrade mask of insight

---

Arcana/mapgen_basements.json
Arcana/mapgen_chaliceimpact.json
Arcana/mapgen_cleansingflame.json
Arcana/mapgen_sanguine.json

* Converts the braziers from traps to furniture. Updated build of CDDA or Coolthulhu's Patch will be needed.
Thanks to Dean over in the Dwarf Fortress discord for pointing this out, because *AAAAH* the bloody thing @Night-Pryanik PR'd was merged literally a week ago and I never noticed it.

Brazier conversion, trap to furniture

---

Arcana/magic_signs.json

Fireball Magic sign was set to shoot acid instead of fire

Fireball fix

---

Arcana/NC_FILES.json
Arcana/crafting_requirements.json
Arcana/furniture.json
Arcana/recipe_deconstruction.json
Arcana/recipe_weapon.json
Arcana/tools.json

Self-PRing mostly because I didn't think I'd get enough time today to finish this batch of ideas up, and thought I might have to do a commit-for-remote to bounce it from laptop to desktop.
* Made it so that you can toggle candle of warding on and off, granting a small amount of light when active. Also made it so that an active candle of warding counts as a valid tool when crafting with recipes that require ritual lighting.
* Gave deployed candle barriers USABLE_FIRE, per a suggestion I received.
* Some proposed rebalances of talisman items. Lowered volume and no longer needs cutting quality to make, and moreover flame talismans have multiple uses.
* Some tweaks to speed of firestarting items so that flame talisman's ignition speed is more noticeable relative to the other arcane items.
* …

Assorted stuff

---

Arcana/mapgen_variants.json

plumber_gear changed to hardware_plumbing to go with recent mainline item group update
ref CleverRaven/Cataclysm-DDA#29260

Update mapgen for item group change

---

Arcana/mutations.json

Obligatory self-PR for feedback.
* Reduced heat protection of Elemental Affinity. It still likely will make wading through fire rather less damaging, but less likely to be 100% immunity.
* Added both static and covered encumbrance to Scaly Wings as well as Draconic wings. Net increase is effectively +5 encumbrance for either if wearing anything on the torso.
* Split the encumbrance for Curved Claws between static and covered, instead of only taking effect when wearing gloves. They would still mess with delicate actions, after all.
* Basically doubled the encumbrance for both Scaly Hind Limbs and Draconic Hind Limbs, via adding both static encumbrance and covered encumbrance to both. Also increased the movecost buffs AND debuffs for both leg mutations.
* Removed dexterity buffs from leg …

Rebalancing Dragonblood

---

Arcana/item_groups.json
Arcana/mapgen_grove.json
Arcana/mapgen_variants.json

* Added a variant to part of the upper levels of gothic churches. There's now a chance that one of the rooms will have signs of a dead inhabitant, implied to have been a stranded mage hunter.
* Added a variant to bookstores. There's a chance that the backroom will have been used for some shady dealings, with locked-up rewards and a few nasty critters to deal with...
* Added a variant to mortuaries, implying that the mortician was doing worse than just harvesting CBMs for the black market...
* Added a variant to abandoned storefronts, that was in use by some people up to no good.
* Added a house variant too, implying a run-down/abandoned house occupied by one or more former arcanists, with one of three potential different outcomes...

More Mapgen Variations: Urban

---

Arcana/ranged.json
Arcana/spells.json
Arcana/tool_armor.json

* Added a 1 in 5 chance of zapping a target when hitting them with a symbol of judgment.
* Added a poison effect to melee damage dealt with the bane staff.
* Overhauled how amber halo and meteoric talisman get their protection. Amber halo is now basically only good against electricity fields with slight resistance to melee zaps, while meteoric talisman gives increased protection that further reduces damage. Now the PoTV ward spell is the only source of complete immunity to lightning.
* Minor enchantment bonus when wearing an active mask of insight.
* Also fixed the meteoric talisman being basically unusable, now it reloads properly and can be turned on.
* Minor name length fix.

Enchantment extra stuff, part one

---

Arcana/TALK_BONE_SEER.json

Self-PRing to snag a bit of feedback, hopefully. This adds some dialogue to arcana specific to the NPC introduced in https://github.com/CleverRaven/Cataclysm-DDA/pull/33828, fleshing out interactions when the player-character has prior experience in the arcane.
* Characters with any of the notable arcanist traits (professions, as well as Paragons of The Veil and Dragonbloods) get some added dialogue after completing the bone seer's mission, which can lead to them potentially offering an arcane monsterpart. Just a bit of flavor dialogue that adds to their interaction, with the selection of parts that get an interesting response being specifically ones used to create a bone charm.
* Paragon of The Veil characters can muse on the nature of this implied cycle when the subject of ending it …

Mod Interaction: The Bone Seer

---

Arcana/effects.json
Arcana/items/comestibles.json
Arcana/monsters/monsters.json
Arcana/mutations/mutations_dragonblood.json

Preparation for https://github.com/CleverRaven/Cataclysm-DDA/pull/41219
* Set it so that red potion's effect blocks the extra effects of blood loss, and consuming it gives a hefty dose of blood and red blood cells.
* Updated medical items so that they reduce bleeding at expected rates.
* Set various effects that halt bleeding to also disrupt anemia and hypovolemic shock. In practice though, since there's no way for spells or effects to generate vitamins, I suspect this won't be as useful as halting blood loss would be.
* Set it so that Dragonblood mutants gain bonuses to blood recovery, scaling up as their main metabolic traits evolve (since those are the ones that affect healing rate)
* Removed use of oboslete monster flag.

[WIP] Preparation for blood overhaul

---

Arcana_BN/recipes/recipe_armor.json

Bolstered Iridescent Brooch ("brooch_iridescent_empowered") currently uses Exotic Amulet as an ingredient instead of Iridescent Brooch. This code change proposes to substitute the latter, more intuitive ingredient in its recipe.

Bolstered Iridescent Brooch Recipe Fix

---

Arcana/modinfo.json
Arcana/monsters/monster_drops.json
Arcana_BN/modinfo.json
Arcana_BN/monsters/monster_drops.json

Self-PR'd so I'd be able to chuck it at Noct to see what they think of it.
* Set it so that augmented abominations, living or undead, can potentially drop blood essence. Both also have a chance of dropping a twisted bone, a wind fragment, or an acrid fragment.
* Fungal augmented abominations get a separate itemgroup injection that changes up the essence drop to randomly being either normal essence or blood essence (standardized for fungalized monsters by https://github.com/chaosvolt/cdda-arcana-mod/commit/28a3d50576020f4d5a3591d45b84559b969b1457), and a reduced chance of dropping the normal abomination monsterpart, in exchange for a second roll to potentially drop either a barbed stinger or an inflorescent root (common fungal creature drops).
* Set Apophis to drop boss-level amount of …

Add mod-compatibility monsterdrops for Cata++ monsters

---

Arcana_BN/chargen/professions.json
Arcana_BN/chargen/scenarios.json

This PR changes the profession Arcane Purifier and add the Arcane Operator profession. Changed and additions are as follows:
Arcane Purifier - Changed made took into consideration two things, a point cost of 8 and the fact that this profession is tied to the Urban Awakening scenario which limits its starting options. Removed the bionic metabolics cbm making this profession dependent on batteries and it's capacitance spell; running out of bionic energy mid fight is a possibility now and was added to address other changed. Gave it both the Bionic toolset and the Bionic internal clock. Both give flavor to what this profession is and make it distinct from the other, the watch is just for flavor than use. gave it the bionic cranial flashlight to allow it to craft in a pinch, useful for being …

Additions to the Urban Awakening Scenario and its professions.

---

Arcana/items/tool_armor.json

Cyclopean mirror lacks pocket data in DDA, so essence can't be loaded into it. Used BN max charges for ammo amount.

Fix cyclopean mirror for DDA branch

---

Arcana/mutations/mutation_category.json

Without this, C:DDA will try look for the empty ("") vitamin and mutation will never occur since it doesn't exist in the player. The null vitamin bypasses that check.
Tested with Blood Effigy, Sacramental Heart, and Restored Ritual Blade.

Use "null" vitamin for mutation categories.

---

Arcana/items/tools.json

Make Candle of Warding capable of lighting fires by action and light fires in furniture such as Smoking racks
Alternatives Considered:
That the Candle of Warding has a magical light that gives no heat and can create to no other flame. In which case ignore this

Update tools.json. Make active Candle of Warding a firestarter

---

Arcana/recipes/recipe_weapon.json

Summary:
Change VeilBlade recipe to require both Oaths to The Chalice AND Sanguine Codex
Purpose of Change:
In the Blade Purification quest, the Hermit says that:
>The main things you will need are His sacred word, Oaths to The Chalice.  You'll also need to consult Sanguine Codex to decipher the original spell.
However the recipe "Restored Ritual Blade" requires Oaths to The Chalice OR Sanguine Codex, contradicting the Hermits words of needing both
Solution:
Make the two books seperate requirements for the recipe rather than substitutes for each other
Also the book "book_syncretism" which is the A Story in Shadow is nowhere mentioned by the hermit. If this is still a valid book, I'll add it back in if you want me to.
Alternatives considered:
The hermit lied to me :(

Fix VeilBlade AKA Restored Ritual Blade recipes book requirements

---

Patchmods/DDA_Arcana_Dinomod_Patch/monsters.json

When looking at original monsters file, I see that it lists 78 monsters,
of 3 varieties, shady/skeletal/fungal, making it a total of 26 dinos evolved.
In current version of DinoMod, there are many more dino types thah that.
The current commit updates the total number to 161.
It works in my current innawood game, tested by starting new world with Innawood, Arcana, DinoMod and the Dinomod patch, spawned 10 skeletal dinosaurs, and killed them via debug menu. Some (not all) dropped essence and other arcana items.

Add many more dinos to monsters.json for chance to drop Arcana loot

---

Arcana/ammo_effects.json
Arcana/field_type.json
Arcana/item_groups/item_groups_general.json
Arcana/item_groups/item_groups_sanguine.json
Arcana/item_groups/item_groups_vanilla.json
Arcana/items/ranged.json
Arcana/items/tools.json
Arcana/martialarts.json
Arcana/npcs/NC_FILES.json
Arcana/recipes/recipe_deconstruction.json
Arcana/recipes/recipe_weapon.json
Arcana/spells/spells_react.json
Arcana_BN/ammo_effects.json
Arcana_BN/field_type.json
Arcana_BN/item_groups/item_groups_general.json
Arcana_BN/item_groups/item_groups_sanguine.json
Arcana_BN/item_groups/item_groups_vanilla.json
Arcana_BN/items/ranged.json
Arcana_BN/items/tools.json
Arcana_BN/martialarts.json
Arcana_BN/npcs/NC_FILES.json
Arcana_BN/recipes/recipe_deconstruction.json
Arcana_BN/recipes/recipe_weapon.json
Arcana_BN/spells/spells_react.json

Implement a new weapon for sanguine shrikes

---

Arcana/field_type.json
Arcana/mutations/mutations_dragonblood.json

Due to https://github.com/CleverRaven/Cataclysm-DDA/commit/4840ee2e553ca74e14f3bbd624750cc51766ec8f 
(Limbify/flagify field immunity)
Of course you can modify the flag name to the one you like.
I evaluated `BRRR_FOG_IMMUNE`, `OH_SHIT_ITS_COLD_IMMUNE`, `COLD_FOG_IMMUNE`, `DEADLY_FOG_IMMUNE`.

Fix field immunity in DDA version

---

Arcana_BN/monsters/monster_overrides.json
Arcana_BN/monsters/monsters.json

To be merged after https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1945 is merged, which renders tweaks to vanilla vortices unneeded.

Pending BN updates: vortices

---

Arcana/monsters/monster_drops.json
Arcana/monsters/monster_overrides.json

Noticed while playing that `small slimes` weren't dropping `slime_scrap` so went ahead and fixed that.
`Amoebic mold` also wasn't dropping samples so included a fix for that (possibly other monsters with that problem).
Did in-game testing to make sure it worked, feel free to change this however you like.

Monster drop fixes

---

Arcana/martialarts.json

In experimental unarmed weapons have been significantly reworked. Now it only include "worn" weapons like knuckles, plus some normal armor also provide unarmed damage bonus. Claws, on the other hand, does not considered to be unarmed weapon any more. I added second version of this buff that would work with claws specifically and also add ability to used unarmed variant with unarmed weapons like mentioned in json note.
While not directly relevant to this pr, i would like to hear feedback about specifying compiteble weapons based on categories rather then specific weapons\damage types. So for example Via Gladium et Malleo would require "MEDIEVAL_SWORDS" category rather then cut damage of 20 or more. That would increase compatibility with other mods and reduce need to manually update weapon …

Honed claws buff fix

---

Arcana/items/tool_armor.json

I adjust abyssal armor to be more inline with vanilla plate armor. More specificaly, i made it somewhat in between light and medium plate armor as i want it to be relatively unencumbering(to let you kill staff more efficiently) but i also want it to be relativly close to berserker armor aesthetically, as it is look very imposing. So i decided that would be the best option

Berserker armor adjustment

---

Arcana/vehicleparts.json

Due to https://github.com/CleverRaven/Cataclysm-DDA/commit/89a86fc094b316fa8d8e23d7be6040a07cfe25cd

Change vehicle energy_consumption to watts

---

Arcana_BN/items/tool_armor.json
Arcana_BN/items/tools.json

Work set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2284 is merged, easy enough. I need to prep one for Cata++ soon too.
Also includes phasing out AEP_PSYSHIELD in favor of the PSYSHIELD_PARTIAL flag, and calling for psychosis trait instead of using AEP_SCHIZO, as is done in the DDA version. Though my intent is for BN to have access to those features in some way via relicgen or item/effect flags later on, might as well just in case I forget prior to arti-effects finally getting phased out in favor of whatever relicgen implementation we're able to do in BN.

Convert remaining art-effects in BN version

---

Arcana/overmap_and_mapgen/mapgen_variants.json

Noticed it during my gamplay, confirmed it after fiddling with map editor a bit. This particular tile apreas way more often then any other. I changed it to be part of nested mapgen as other tiles and it seems to be fine now.
I only tested it with map editor tho, so probably need to see in actual game world as well to be sure
Edit: tested, was able to fine a few after a fix, not nearly as omnipresent as it used to be

Arcana microlab_generic_tile variant generata a lot more often then any other

---

Arcana/mutations/mutations_dragonblood.json

My preveous change made charecter unable to  get Draconic Muzzle without high instability as it is considered a negative trait, also made Draconic Hind Limbs equal to Toe Talons, as I underestimate how deadly they are for mutation tree that give a ton of strength

Dragonblood mutation fixes

---

Arcana/mutations/mutations_dragonblood.json

Added SAPIOVORE trait, becouse eating scaleless apes seems fitting for these mutation tree and dense bones(new mutation which is shared by all mutation trees that increase charecter size and few others). changed Elemental Affinity to affect temperature with climate control enchantment, as it is a lot more straight forward and actually allow you to not suffer from heat strokes during summer. Also adjusted Metabolic Resilience tree. Currently, even the 1 level makes you essentially immune to toxin. Now 1 one would halve the toxins you absorb and double the recovery speed, which is still pretty good, and second will make you immune. And lastly changed tail gear restriction to be in line with others

more Dargonblood tweaks

---

Arcana_BN/achievements.json

Set aside as a self-PR for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2613 is merged, using the new achievement format introduced in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2719 so that skill achievements don't shit themselves if you start with enough chargen skill to exceed the achievement's target skill level.

Pending BN Updates: Skill Achievement Improvements

---

Arcana_BN/chargen/professions.json
Arcana_BN/chargen/scenarios.json

This sets aside some stuff for when/if https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2892 is merged, adding content to inject into the new Lost And Damned scenario.
Profesions:
1. Feral mage hunter, based directly after the mage hunter profession but swapping in the variant gear that maddened hunters have a chance to drop instead.
2. Feral sanguinist, likewise an adaptation of the blood mage profession but adding some shrike gear which the maddened sanguinist can drop.
3. Feral keeper, adaptation adds in the spear of pestilence and cyclopean shield in addition to swapping in variants of the mantle and gauntlets.
4. Feral summoner, beefed up a bit from the basic version but otherwise not that divergent for a feral version of the summoner profession.
Scenario edit also adds in the …

Pending BN update: The Lost And Damned

---

Arcana/recipes/recipe_weapon.json
Arcana_BN/recipes/recipe_magitech.json
Arcana_BN/recipes/recipe_weapon.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3008 is merged, phasing in usage of the new tiers of blacksmithing 
Also shifts shrike's misericorde to not use a swage and die since mostly made of silver, contains a slight tweak to the DDA version of the recipe accordingly.

Pending BN update: anvil usage overhaul

---

Arcana_BN/mutations/mutations_other.json

Set aside as a draft for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2911 is merged, as now custom dialogue flags for mutations need their own definitions as `mutation_flags` entries.

Pending BN Update: Mutation Flag JSON

---

Arcana/chargen/professions.json
Arcana/item_groups/item_groups_chalice.json
Arcana/item_groups/item_groups_cleansingflame.json
Arcana/item_groups/item_groups_general.json
Arcana/item_groups/item_groups_sanguine.json
Arcana/monsters/monster_drops.json
Arcana/npcs/NC_FILES.json

Shifts items to spawn with 'count' instead of 'charges' as charges have been deprecated in CDDA
Adds "sewing_room" and "mine_storage" itemgroups to generic file as these groups have been deleted from CDDA but are still used in Arcana

Fix charges -> counts and adds deleted item groups to give CDDA compatability

---

Arcana/skills.json

Currently the Arcana skill is between the ranged and crafting skills while being an interaction skill.
Issue (metaphysics and spellcraft are mod skills):
Fix:

Group Arcana skill with other interaction skills

---

Arcana/techniques.json

https://github.com/CleverRaven/Cataclysm-DDA/pull/68418 removed the powerful_knockback field.
The field didn't do anything even before deprecation, so I'm following 68418 as an example by not replacing the field with anything.

Remove powerful_knockback field from DDA techniques

---

Arcana/spells/spells_magic_signs.json

Context:
CDDA added a feature where the spell menu allows sorting by spell class, ex:
Since many of the spell signs have unique spell classes, this massively clutters the menu with many individual tabs for each sign.  Removing the classes fixes this.
I created a character with the removed classes and they still spawn with the correct spells when added via profession / chargen traits:

Remove Spell Classes from Magic Signs

---

Arcana/items/books.json
Patchmods/BN_Arcana_Cata++_Patch/books.json

CDDA added the 'manual' category to skillbooks in [#53852](https://github.com/CleverRaven/Cataclysm-DDA/pull/53852#issue-1090194548) .  Adding this category to skillbooks in Arcana so there isn't a mismatch.

Add 'manual' category to skillbooks

---

Arcana_BN/item_groups/item_groups_vanilla.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3769 is merged, which adds a new bionic itemgroup for military stuff.
Additionally, belatedly added an itemgroup injection to `bionics_mil`.

Pending BN update: new bionic itemgroup

---

Arcana_BN/items/armor.json

Set aside as a draft for if https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3792 is merged. All it does is add `COMPACT` to satchel of eternity, as if it matters much given how much storage it has.

Pending BN feature: accessories with COMPACT flag

---

Arcana_BN/furniture_and_terrain/traps.json

For when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3941 is merged, sets the relevant traps to have the new `remove_on_trigger` bool.

Pending BN Update: trap updates

---

Arcana_BN/chargen/professions.json
Arcana_BN/npcs/NC_FILES.json

Simple lil thing set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4106 is merged, only change that ended up being needed for now is giving arcane purifier profession the new infolink CBM instead of bionic watch, and making it so the purifier NPCs can potentially have them due to it having been made NPC installable.

Pending BN Update: Bionic Infolink

---

Arcana/spells/effect_on_condition.json

Some time stuff is now handled with math since https://github.com/CleverRaven/Cataclysm-DDA/pull/70996.
Beware, there are a lot more changes like this coming soon, I'm afraid.
Like here: https://github.com/CleverRaven/Cataclysm-DDA/pull/71216
Don't like how CleverRaven gets mentions on their end, because of links, is there any way to stop that?
It seems it's too late to change the mentions now, *sigh*.

"time" changed to math.

---

Arcana_BN/items/tools.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4174 is merged, adds `ACT_ON_RANGED_HIT` to summoning glyphs to allow deploying them by throwing, since that PR will make it work properly.

Pending BN Update: "I choose you, Yog-Sothoth!"

---

Arcana/furniture_and_terrain/furniture.json
Arcana_BN/furniture_and_terrain/furniture.json

Simple lil self-PR set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4129 is merged. Applies the newly-available damage resistance feature to fitting furniture items in the mod. Which means now candle barriers actually work as barriers. :>

Pending BN Update: Take Cover!

---

Arcana_BN/monsters/monster_drops.json
Arcana_BN/monsters/monster_factions.json
Arcana_BN/monsters/monster_overrides.json
Arcana_BN/monsters/monsters.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4182 is merged.
1. Added death drop override for lepidopterid, currently same as wraiths.
2. No longer have to inject death drop itemgroup into gozu since it gains vanilla death drops the items are now being added to.
3. Updated override for nether faction to preserve the added neutrality with zeds.
4. Update flag changes for summoned yuggs.

Pending BN Update: Nether Updates

---

Arcana/npcs/factions.json

https://github.com/CleverRaven/Cataclysm-DDA/pull/71546 altered how faction food supply definitions work, among other things
I'm not entirely sure what justification was used for giving some factions vitamins but other factions no vitamins, but I believe its reasonable that if factions have an established food supply that they also have some relevant vitamins as well.

Update DDA faction food supply definitions

---

Arcana/monsters/monsters.json

STARE attack is now a spell, see https://github.com/CleverRaven/Cataclysm-DDA/pull/71624

[DDA] Move STARE to spell

---

Arcana/mutations/mutations_dragonblood.json
Arcana/mutations/mutations_other.json

CDDA deprecated these values in favor of enchants.  Ported them over

Port mutation values to enchantment values

---

Arcana/overmap_and_mapgen/mapgen_variants.json

https://github.com/CleverRaven/Cataclysm-DDA/pull/72164 changed the palette ID to another one.
It also added another id to enable vandalized variants but in the name of keeping functionality the same I used the one with the same current function.

Update palette ID

---

Arcana_BN/vehicleparts.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4293 is merged, uses the new `vehicle_repair_electronics` for magitech vehicleparts.

Pending BN Update: vehicle repairs cost materials

---

Arcana/monsters/monstergroups.json
Arcana/mutations/mutations_dragonblood.json
Arcana/mutations/mutations_other.json
Arcana/overmap_and_mapgen/mapgen_variants.json

Some more stuff moved to enchantments. Not sure if the new MENDING_MODIFIER values are set correctly though. GROUP_MANSION was removed and replaced with GROUP_MANSION_START which is only used for mansion starts, if that's how you'd like it then the changes should work as is, if not that'll need changing as well.

Changes to match upstream updates

---

Arcana/ammo_effects.json
Arcana/furniture_and_terrain/ter_furn_transform.json
Arcana/overmap_and_mapgen/mapgen_variants.json
Arcana/spells/spells_aftermath.json
Arcana/spells/spells_sanguine_marks.json

This got changed back in DDA: https://github.com/CleverRaven/Cataclysm-DDA/pull/73958

Change fd_reality_tear back to fd_fatigue

---

Arcana/techniques.json

In https://github.com/CleverRaven/Cataclysm-DDA/pull/73064 the format for attack_vector definitions changed to allow for extra specificity/unhardcoding/etc.  This PR converts the old attack vector definitions to the new ones based on the linked PR's example with the DDA techniques.
Note: The current attack_vector definitions do not throw a startup error but will fail when actually trying to use them.

[DDA] Convert martial arts technique attack_vectors to new format

---

Arcana_BN/items/tools.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5186 is merged, adds `ALLOWS_REMOTE_USE` to relevant `deploy_furn` and `place_monster` items.

Pending BN Update: `ALLOWS_REMOTE_USE` works on more stuff

---

Arcana_BN/modinfo.json
Arcana_BN/vehicleparts.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5429 is merged, sets `folded_volume` for relevant turret vehicleparts.

Pending BN Update: foldable turrets

---

Arcana_BN/item_groups/item_groups_vanilla.json
Arcana_BN/modinfo.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5635 is merged, fixes the injection of items into the `drugdealer` itemgroup since it's getting converted to a collection (which in Arcana gains a chance of arcanist books being run, assumed to be rare black-market deals with lost books).

Pending BN Update: Change to `drugdealer` itemgroup

---

Arcana_BN/items/books.json
Arcana_BN/items/classes.json
Arcana_BN/items/tools.json
Arcana_BN/modinfo.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5698 is merged. Adds the new flag to the item all notes in Arcana inherit from. In addition, arcanist books now have their full description moved to an internal snippet, with the baseline description omitting the flavor quote, and likewise the cursed blade no longer implies illiterate characters can make out a single phrase among the engravings.

Pending BN Feature: `SNIPPET_NEEDS_LITERACY` flag

---

Arcana_BN/mutations/mutations_dragonblood.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5624 is merged, gives Scaly Wings and Draconic Wings the same standard modifiers as all vanilla wings, with a code comment explaining why Draconic Wings uses the standard one currently.

Pending BN Update: Add `falling_damage_mutliplier`

---

Arcana_BN/items/ranged.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5769 is merged, finally magic ranged weapons affected by the "reload time is secretly multiplied by how many reloads are being loaded" bug can have the same reload rate as in the DDA version.

Pending BN Update: magic ranged weapons reload rate sanity-checking

---

Arcana/items/armor.json
Arcana/items/ranged.json
Arcana/items/tool_armor.json
Arcana/items/tools.json
Arcana/monsters/monster_drops.json
Arcana/monsters/monster_overrides.json
Arcana/obsolete.json
Arcana/spells/enchantments.json

Adjusts armor enchants to meet new syntax
Removes mass of zombie spiders drops since that monster was deprecated

DDA Updates

---

Arcana_BN/items/tools.json
Arcana_BN/martialarts.json
Arcana_BN/modinfo.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5994 is merged, switching uses of `HAND_AXES` weapon category for `1H_AXES`.

Pending BN Update: Phasing out of `HAND_AXES` weapon category

---

Arcana/item_groups/item_groups_sanguine.json
Arcana/mod_interactions/magiclysm/monster_drops.json
Arcana/npcs/missiondef.json
Arcana/overmap_and_mapgen/mapgen_basements.json
Arcana/overmap_and_mapgen/mapgen_purifer_ambushed.json
Arcana/overmap_and_mapgen/mapgen_update.json

There was update that causes many errors.
https://github.com/CleverRaven/Cataclysm-DDA/pull/79952 What caused "two mission defenition from same source" was most nasty to locate and figuire out where error.

Ammo Overhaul compatibility update

---

Arcana/npcs/TALK_HERMIT.json

Fixes a couple of lines that use the old syntax
Also changes the chalice dialogue tree to condition on the chalice variable instead of the sanguine variable
Tested by spawning the npc and reaching that point in the questline.

[DDA] Dialogue Fix

---

Arcana/overmap_and_mapgen/mapgen_sanguine_holdout.json

The sanguine holdout had a duplicate terrain field to get rid of the portal overlay.  Unfortunately just moving it into the existing furniture array with f_null didn't actually result in removing the portals from the mapgen, so I just swapped the walls definition from P to Y
Test:
Unfortunately I don't have Bright Nights to test if this fix works there or if its even an issue

[DDA] Fix mapgen duplicate definition

---

Arcana/items/tool_armor.json
Arcana_BN/items/tool_armor.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6270 is merged. Applies the `UNBREAKABLE` flag to active cyclopean mirror and active jade hauberk.

Pending BN Feature: `UNBREAKABLE` flag

---

Arcana/items/books.json
Arcana/items/tool_armor.json
Arcana/items/tools.json
Arcana/monsters/monstergroups.json

Hi,
This is my first time using git so please handle this with appropriate lack of respect for my competence.
Was installing the latest experimental and got a bunch of errors, I went into the files and changed the following and it stopped the errors:
The book fields "fun" and "skill" are now "read_fun" and "read_skill" as per https://github.com/CleverRaven/Cataclysm-DDA/pull/80490
The tool ammo field "ammo" is now "tool_ammo" as per https://github.com/CleverRaven/Cataclysm-DDA/pull/80490
"weight" field no longer accepts int, added changed from eg 123 to "123g". Note there were only int values in the relative section on those files, and I'm not 100% on what that function does so hopefully it doesn't break anything. I assumed the weights were in grams.
"starts" field also no longer accepts …

Update some field names and weight formats to work with DDA changes

---

Arcana/mod_interactions/magiclysm/martialarts.json

Via Gladium et Malleo can be used with mage blade(former holy blade) from technomancer class.

Via Gladium et Malleo & Magiclysm

---

Arcana_BN/items/tool_armor.json
Arcana_BN/items/tools.json
Arcana_BN/modinfo.json

Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/7079 is merged, gives several items in Arcana the ability to be activated by an NPC that happens to be wearing them.

Pending BN Update: NPCs activating equipment in combat
