- Arcana/modinfo.json
Updated the path to the new dependencies.
> Added dependencies

- Arcana/armor.json
- Arcana/books.json
- Arcana/item_actions.json
- Arcana/item_groups.json
- Arcana/mapgen_basements.json
- Arcana/mapgen_grove.json
- Arcana/materials.json
- Arcana/recipe_armor.json
- Arcana/recipe_deconstruction.json
- Arcana/recipe_others.json
- Arcana/tools.json
Self-PRing mostly because fuck it, better way to get feedback than just committing it.
This is stuff that @cddaDeoxy (assuming that's them on here) suggested ages ago. As in farthest ago I can find is back in august 2016.
Adds a few items:
* Satchel of eternity. Yep, it's a bag of holding. Pretty much the first purely passive item added to the mod. Adds a hefty amount to carrying volume and weight, but wearing it also inflicts nether attention and teleportis. What did you expect, from what's basically a stablized portal stuffed into a pouch?
* Druidic staff. Deoxy also suggested a magical repair item. For theme reasons I went with a smattering of materials that might vaguely count as natural. This means no snythetic materials or metals, but does include otherwise-irrepreable materials …
> Implement Deoxy's Magic Item Ideas

- README.md
Just adds a smol description for the new candle, once it works.
> Readme Addition

- Arcana/tools.json
Might do more later, but I'll see if this pans out first.
> Added copy-from to Veinreaver from vanilla hatchet

- README.md
I'll need a few hints to what looks good and what needs to be changed @chaosvolt.
> [CR] Prettification of the README.md

- Arcana/monsters.json
Preparation for https://github.com/CleverRaven/Cataclysm-DDA/pull/38585
> Update syntax of monster spellcasting

- Arcana/vehicleparts.json
DEBUG : vehicle part distorion_amp_motor_part has unknown flag EMITTER
FUNCTION : static void vpart_info::check()
FILE : src/veh_type.cpp
LINE : 683
After upgrade to latest mod version
I'm on latest CDDA experimental release
> fix: vehicle part distorion_amp_motor_part has unknown flag EMITTER

- Arcana/items/armor.json
- Arcana/items/tool_armor.json
- Arcana/monsters/monstergroups.json
- Arcana/npcs/NC_FILES.json
Update monster groups thanks to waveyl's work, add speech skill to an NPC as a replacement for barter skill just like in vanilla, update armor thanks to Anothersimulacrum's script as well
> Update monster groups thanks to waveyl's work, add speech skill, update armor thanks to Anothersimulacrum's work 

- Arcana/npcs/TALK_HERMIT.json
- Arcana/npcs/TALK_MARLOSS_VOICE.json
- Arcana/npcs/missiondef.json
A fix to the JSON error caused by the trait flag changes outlined in DDA changelog #55061.
> JSON load error fix

- Arcana/npcs/missiondef.json
- Arcana_BN/npcs/missiondef.json
Run the tool added in https://github.com/CleverRaven/Cataclysm-DDA/pull/55489 as a CI job
then fix the errors it finds
> Clear missing .om_special in missions

- Arcana/items/tool_armor.json
- Arcana_BN/items/tool_armor.json
First off, I enjoy your mod, thanks.
Second, here's some minor contribution for the cyclopean mirror.
> Fix typo, missing action menus

- Arcana/materials.json
- Arcana/vehicleparts.json
Due to https://github.com/CleverRaven/Cataclysm-DDA/pull/60607
> Fix fuel energy consumption in DDA version

- Arcana/items/tool_armor.json
https://github.com/CleverRaven/Cataclysm-DDA/pull/61139 removed ´CLIMATE_CONTROL´.
> CLIMATE_CONTROL was deprecated.

- Arcana_BN/monsters/monster_drops.json
Drop rate tweaks that can go into effect once https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1947 is merged.
> Pending BN updates: shadows

- Arcana/items/tools.json
- Arcana_BN/items/tools.json
Reverts chaosvolt/cdda-arcana-mod#301
See https://github.com/chaosvolt/cdda-arcana-mod/pull/301#issuecomment-1327959918
> Revert "Display candles of warding as active when active"

- Arcana/items/melee.json
- Arcana/items/ranged.json
- Arcana/overmap_and_mapgen/mapgen_variants.json
- Arcana/recipes/recipe_ammo.json
- Arcana/recipes/recipe_magitech.json
- Arcana/recipes/recipe_others.json
- Arcana/recipes/recipe_weapon.json
probably coused by pr #64399 that removed some obsolated content
> Fixes for some obsolated stuff

- Patchmods/BN_Arcana_Aftershock_Patch/modinfo.json
- Patchmods/BN_Arcana_Cata++_Patch/modinfo.json
- Patchmods/BN_Arcana_Dinomod_Patch/modinfo.json
- Patchmods/BN_Arcana_Magiclysm_Patch/modinfo.json
makes the 'Arcana' to <color_cyan>
> Bright Nights Patchmod coloring

- Arcana_BN/npcs/TALK_OLD_GUARD_NEC_COMMO.json
- Arcana_BN/npcs/TALK_OLD_GUARD_NEC_CPT.json
Minor update hinging on an open PR in BN: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2686
Will merge it when that's done.
> Pending BN Update: Necropolis Update 2

- Arcana_BN/items/tools.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2846 is merged.
> Pending BN update: straw items made out of dry_plant, can be repaired

- Arcana_BN/chargen/scenarios.json
Simple lil thing set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2908 is merged, adding sanguine shrikes and arcane operatives to the new scenario.
> Pending BN update: One Last Assassination

- Arcana_BN/achievements.json
- Arcana_BN/monsters/species.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2720 is merged.
> Pending BN Update: species name

- Arcana/spells/effect_on_condition.json
Update the EOCs to match upstream changes.
> eoc/Arcana: use math instead of arithmetic

- Arcana/monsters/monster_overrides.json
- Arcana/monsters/monsters.json
> Convert FEAR_PARALYZE to spell as DDA jsonized it

- Arcana/items/melee.json
- Arcana/monsters/monsters.json
> EoCify STARE monattack

- Arcana/mutations/mutations_dragonblood.json
- Arcana/mutations/mutations_magic_signs.json
- Arcana/mutations/mutations_other.json
- Arcana/mutations/mutations_paragon.json
Like the title says, updates to reflect changes in https://github.com/CleverRaven/Cataclysm-DDA/pull/72173
> Update to replace modifiers with enchantments to reflect upstream changes

- Arcana/ammo_effects.json
- Arcana/effects.json
- Arcana/furniture_and_terrain/ter_furn_transform.json
- Arcana/items/ranged.json
- Arcana/monsters/monster_drops.json
- Arcana/mutations/mutations_magic_signs.json
- Arcana/overmap_and_mapgen/mapgen_variants.json
- Arcana/spells/spells_aftermath.json
- Arcana/spells/spells_item.json
- Arcana/spells/spells_magic_signs.json
- Arcana/spells/spells_sanguine_marks.json
> Rename fatigue to sleepiness & Strip ferals from guns

- Arcana/martialarts.json
Missed one unarmed_weapons_allowed in fix for recent dda change
> Fix one missed unarmed_weapons_allowed

- Arcana_BN/furniture_and_terrain/furniture.json
- Arcana_BN/furniture_and_terrain/terrain.json
- Arcana_BN/modinfo.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5582 is merged, updates relevant terrain and furniture in BN version.
> Pending BN Update: more updates to ranged bash info

- Arcana/chargen/professions.json
I'm not too familiar with the mod, maybe more audit?
> battery audit

- Arcana/mutations/mutations_dragonblood.json
- Arcana/spells/effect_on_condition.json
updates the following
- adjusts for the new enchantment item damage format
- adjusts for the new queue eoc format
> [DDA] more updates

- Arcana/overmap_and_mapgen/mapgen_basements.json
Somehow couple errors did't pop up
> Another ammo fixes

- Arcana/items/ammo.json
Changed exotic arrows and bolts to use the updated recovery chance definition.
CleverRaven/Cataclysm-DDA/pull/74667
CleverRaven/Cataclysm-DDA/pull/73931
> Fix arrow bolt recovery chance

- Arcana/overmap_and_mapgen/mapgen_cleansingflame.json
- Arcana/overmap_and_mapgen/mapgen_lab_arcane.json
- Arcana/overmap_and_mapgen/mapgen_variants.json
https://github.com/CleverRaven/Cataclysm-DDA/pull/80903
> updating itemgroups

- Arcana/mod_interactions/Cata++/books.json
- Arcana/mod_interactions/Cata++/melee.json
- Arcana/mod_interactions/Cata++/recipe_magitech.json
Just a couple of edits to mod_interactions/cata++ folder. I was gonna do the item groups but it looks like I was already beat to that for Arcana.
> Cata++ mod interactions update

- Arcana_BN/chargen/professions.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/7029 is merged, updates the feral professions to be up to date with how the others are flavored.
> Pending BN Update: feral profession updates
